# Generated by Django 3.1.4 on 2021-02-01 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_auto_20210127_1132"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fpluser",
            name="consent",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
