# Generated by Django 3.1.4 on 2021-02-03 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_auto_20210201_1309"),
    ]

    operations = [
        migrations.AddField(
            model_name="league",
            name="period",
            field=models.IntegerField(
                choices=[(1, "weekly"), (2, "monthly")], default=1
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="fpluser",
            name="consent",
            field=models.BooleanField(default=False),
        ),
    ]
