# Generated by Django 3.1.4 on 2021-02-04 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_prize"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="prize",
            name="league",
        ),
        migrations.AddField(
            model_name="league",
            name="prize",
            field=models.ManyToManyField(blank=True, to="api.Prize"),
        ),
    ]
