# Generated by Django 3.1.4 on 2021-02-04 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_auto_20210204_0635"),
    ]

    operations = [
        migrations.AddField(
            model_name="gameweekhistory",
            name="league",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="api.league"
            ),
            preserve_default=False,
        ),
    ]
