# Generated by Django 3.1.4 on 2021-02-07 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_gameweekhistory_league"),
    ]

    operations = [
        migrations.AddField(
            model_name="fpluser",
            name="address",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="fpluser",
            name="dob",
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name="fpluser",
            name="phone",
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name="fpluser",
            name="username",
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
