# Generated by Django 3.1.4 on 2021-02-10 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_auto_20210207_1615"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fpluser",
            name="team",
        ),
        migrations.AddField(
            model_name="team",
            name="captain",
            field=models.ForeignKey(
                blank=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team_captain",
                to="api.player",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="team",
            name="vice_captain",
            field=models.ForeignKey(
                blank=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team_vice_captain",
                to="api.player",
            ),
            preserve_default=False,
        ),
    ]
