# Generated by Django 3.1.4 on 2021-02-10 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_auto_20210210_0822"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="captain",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team_captain",
                to="api.player",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="vice_captain",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team_vice_captain",
                to="api.player",
            ),
        ),
    ]
